### ISSUE TITLE
Attributes?

### ISSUE THREAD

**Issue by Naphier** [mgholam/fastJSON#36]
Are there attributes for serializing private fields and ignoring public properties like Json,Net has: 
```
[JsonProperty("statuses")]
private SimpleTweet[] statusesIn;
[JsonIgnore]
public SimpleTweet[] statuses;
```
I tried `[XmlElement(ElementName = "statuses")]` and could not find any usage examples in your unit tests.
Thanks.

PS: .NET35 version

**Comment by mgholam** [comment]
Currently only `XmlIgnore` and `NonSerialized` is supported.

Personally I don't like to add attributes, since it bloats and makes understanding the code more difficult (you have to post process and mentally compile what you are reading...) 

But I understand the need in certain circumstances, I will try to add something like this in the future.

**Comment by Naphier** [comment]
Yeah, the need is two-fold. 

1. APIs often use names on variables that go against coding guidelines (and change these names in future API versions).
2. The allowance of serializing private variables (or variables with accessors) enables developers to maintain good programming practices (member access restriction) in a single class instead of writing a DAO _and_ a BO. Really one of my favorite things about Json.NET.

Cheers!
