### ISSUE TITLE
Does Unity Game Engine Supported?

### ISSUE THREAD

**Issue by EmpireWorld** [mgholam/fastJSON#49]
Can i import fastJSON to my unity project?

Does unity supported?

**Comment by mgholam** [comment]
I don't know, try and see.

**Comment by EmpireWorld** [comment]
Which .NET versions are supported?

**Comment by EmpireWorld** [comment]
I have tried it in Unity but throws an exception in compilation:

```
The type or namespace name `Data' does not exist in the namespace `System'. Are you missing `System.Data' assembly reference?
```

and many more.

**Comment by mgholam** [comment]
v2+ and mono 
[https://www.codeproject.com/Articles/159450/fastJSON](https://www.codeproject.com/Articles/159450/fastJSON)

**Comment by mgholam** [comment]
Try adding a `SILVERLIGHT` compiler directive.

**Comment by EmpireWorld** [comment]
Where? to your code?

**Comment by EmpireWorld** [comment]
But you have this at your JSON.cs at line 5:

```csharp
#if !SILVERLIGHT
using System.Data;
#endif
```

**Comment by mgholam** [comment]
[https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/define-compiler-option](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/define-compiler-option)

**Comment by EmpireWorld** [comment]
I have added `#define SILVERLIGHT` in JSON.cs but the error exists.

**Comment by EmpireWorld** [comment]
I got a new exception when i added SILVERLIGHT directive:

```
InvalidProgramException: Invalid IL code in (wrapper dynamic-method) UnityEngine.Vector3:_ (object): IL_0013: ret
```

**Comment by iodev** [comment]
It works fine for me in Unity 5.6.1 _Editor_, but when I try to build the WSA (Windows Store) packages, the UWP/WSA configuration cannot find certain namespaces.  When digging, I found this similary thread:
https://forum.unity3d.com/threads/problem-building-for-windows-store-with-windows-10.358037/
and
https://docs.unity3d.com/Manual/windowsstore-missingtypes.html
which does contain all of the items that are exploding in the WSA package, when trying to call fastJSON.JSON.ToJSON(<object>).
I'll fork and try to fix it.  I'm expecting I'll need to make a third lib/project that is specialized for WSA (Hololens Toolkit) / UWP.

**Comment by EmpireWorld** [comment]
The new unity version 2017.1 uses C#6 this might fix the problem, i will give it try.

I will contribute to you if you make a fork.

Thanks.

**Comment by iodev** [comment]
https://github.com/iodev/fastJSON
I pushed up the broken code, with the new project "fastJSON UWP".  Only one file needs repair, and then it should be complete.  Have at it.

Got stuck at the setters/getters since the ILGenerator is not available for the UWP, and instead we need to use System.Linq.Expressions.  So, I'm trying to hack through that documentation, while trying to comprehend what was being achieved with the DynamicMethod/ILGenerator code.

**Comment by EmpireWorld** [comment]
Nice, thanks. Do you have tried it in the new unity version?

**Comment by iodev** [comment]
I did not, because the fastJSON problem is not a problem with the Unity version. Mgholam has done a great job explaining the speed of his solution. With the changes necessary to make a UWP-compatible version, it will be necessary to benchmark it again, especially against the jsonutility solution provided by this new version of Unity, which now has a built-in Json. Unless he wants to compete in the Unity market, it is unlikely necessary to provide this compatibility. FastJson works fine in versions of Unity earlier than 5.6 but has trouble in UWP packages and likely other packages. It has a .NETFramework dependency that is not supported outside of the editor.
